destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code, _blueprint, Rakefile]

# Custom Local Config
ga_tracking_code: "UA-9046230-6"
subsite: labs
subsite_name: Socrata Labs
github_repo: https://github.com/socrata/labs.socrata.com

title: Socrata Labs
icon: fa fa-flask

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
